---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyzer(analyzer)
	stem_generator(stem_generator)
	validator(validator)
	distractor_generator(distractor_generator)
	assembler(assembler)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyzer;
	analyzer --> stem_generator;
	distractor_generator --> assembler;
	stem_generator -.-> validator;
	validator --> distractor_generator;
	assembler --> __end__;
	stem_generator -.-> stem_generator;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
