"""
Validator Node

Simple pass-through validator that accepts all generated questions.
SymPy validation removed due to LaTeX parsing complexity.
"""

from typing import Dict, List
from state import MCQGeneratorState, StemWithAnswer, ValidatedQuestion


def validator_node(state: MCQGeneratorState) -> Dict:
    """
    LangGraph node that validates generated stems.
    
    SIMPLIFIED VERSION: Accepts all questions that pass LaTeX validation.
    SymPy mathematical verification has been disabled.
    
    Args:
        state: Current MCQGeneratorState
    
    Returns:
        Updated state: validated_questions, validation_failures, metrics
    """
    print("\n" + "="*60)
    print("VALIDATOR NODE (SymPy validation disabled)")
    print("="*60)
    
    stems = state["generated_stems"]
    print(f"Validating {len(stems)} generated questions")
    
    validated = []
    failures = []
    
    for i, stem in enumerate(stems):
        print(f"\n[{i+1}/{len(stems)}] Processing: {stem['stem'][:60]}...")
        
        # Only check LaTeX validity - skip SymPy validation
        if not stem.get('latex_valid', True):
            print(f"  ⚠ Skipping due to LaTeX validation failure")
            failures.append({
                'question_id': stem['question_id'],
                'reason': 'latex_invalid',
                'stem': stem['stem']
            })
            continue
        
        # Accept all questions that passed LaTeX validation
        print(f"  ✓ LaTeX valid - accepting question")
        
        validated_q = ValidatedQuestion(
            question_id=stem['question_id'],
            concept_id=stem['concept_id'],
            stem=stem['stem'],
            correct_answer=stem['correct_answer'],
            difficulty=stem['difficulty'],
            validation_score=1.0,  # Assume correct since generated by LLM
            was_corrected=False
        )
        validated.append(validated_q)
    
    # Print summary
    print(f"\n{'='*60}")
    print(f"✓ Validated: {len(validated)}")
    print(f"✗ Failed: {len(failures)}")
    if stems:
        print(f"Success rate: {len(validated)/len(stems)*100:.1f}%")
    
    return {
        "validated_questions": validated,
        "validation_failures": failures,
        "metrics": {
            **state.get("metrics", {}),
            "questions_validated": len(validated),
            "questions_failed": len(failures),
            "validation_rate": len(validated) / len(stems) if stems else 0,
            "questions_corrected": sum(1 for q in validated if q['was_corrected'])
        }
    }
